const initialContent = {
    "tree":
        [
            { "id": "readme", "label": "Read me first!", "type": "information", "data": { "textContent": "<h1>Important!</h1><p>In order to keep the loading times of this web app in check, the author decided to publish the user manual as a separate PDF file.</p><p>Grab it from here:</p><p><a href=\"https://marsiglietti.it/DMWhisper-manual-1.26.0.pdf\">https://marsiglietti.it/DMWhisper-manual-1.26.0.pdf</a></p><p>Enjoy The Whisperer!</p><p>&nbsp;</p>" } },
            {
                "id": "farm", "label": "A farm just out of the town", "type": "menu", "data": {
                    "textContent": "The farm just out of the town", "children": [
                        { "id": "farm-map", "label": "Map of the surroundings of the farm", "type": "map", "data": { "textContent": "", "map": { "setpiece": "farm-setpiece", "density": "3", "grid": "1" } } },
                        { "id": "farm-description", "label": "A description of the farm", "type": "information", "data": { "textContent": "<h1>Description of the farm</h1><p><strong>The farm is located between the city gates, the forest and the wizard's castle, which is located on the hill.</strong><br><i>The farm is run by an old farmer and his wife, who have a 10 year old son.</i><br><strong>The farm is surrounded by a stone wall, with a wooden gate.</strong><br><i>The house is a wooden construction with a thatched roof.</i><br><strong>The farm has a small vegetables garden, a chicken coop, a sheep pen and a pig pen. The farm also has a water well.</strong></p>" } },
                        { "id": "events-farm", "label": "The events around the farm", "type": "table", "data": { "textContent": "<h1>Events around the farm</h1><p><i>Note: this is an example of using a macro to substitute table rolls into descriptive rich text content.</i></p><p>Currently, this is what's happening around the farm:</p><blockquote><p>@@01</p></blockquote>", "table": "farm-events" } },
                        { "id": "npc-farm", "label": "The NPCs encountered at the farm", "type": "table", "data": { "textContent": "NPC near the farm", "table": "farm-npc" } },
                        { "id": "weather-farm", "label": "The weather around the farm", "type": "table", "data": { "textContent": "Typical farm weather conditions", "table": "farm-weather" } }
                    ]
                }
            },
            { "id": "explanation", "label": "Explanation of the example tables", "type": "information", "data": { "textContent": "<h1>The data herein is only an example of rich text content.</h1><p><i><strong>The other items in this menu are:</strong></i></p><ul><li>A rich text content page with a link to the app's manual.</li><li>An example of a sub-menu – inside of it there are a map of the surroundings of the farm, a description of the farm and three tables:&nbsp;<ul><li>The farm weather is a content of type “table”, with no rich text or other kinds of content;</li><li>Farm NPCs is a table where some values are simple strings and others are actually rolls on two other tables (NPC from Castle and NPC from Town).</li><li>The last table is that of the farm events: in it there are simple strings, rolls on the farm animals table and rolls on the farm NPC table which, as seen before, in turn contains rolls on other tables.</li></ul></li></ul>" } }], "tables": [{ "id": "farm-events", "description": "Farm Events", "tags": ["events", "farm"], "rng": [{ "min": 1, "max": 2, "result": "A sound of heavy footsteps in the woods" }, { "min": 3, "max": 4, "result": "A group of Goblins approaching" }, { "min": 5, "max": 8, "prefix": "NPC encounter: ", "table": "farm-npc" }, { "min": 9, "max": 11, "prefix": "You meet an animal: ", "table": "farm-animals" }, { "min": 12, "max": 12, "prefix": "Weather is changing: ", "table": "farm-weather" }, { "min": 13, "max": 15, "result": "A hum of insects coming from the woods" }, { "min": 16, "max": 17, "result": "A whirlwind that kicks up the dust" }, { "min": 18, "max": 18, "result": "A dull thud coming from the woods" }, { "min": 19, "max": 20, "prefix": "Weather is changing: ", "table": "farm-weather" }] },
            { "id": "farm-weather", "description": "Weather around the farm", "tags": ["weather", "farm"], "rng": [{ "min": 1, "max": 1, "result": "Cold and foggy" }, { "min": 2, "max": 4, "result": "Cool" }, { "min": 5, "max": 8, "result": "Wind and rain" }, { "min": 9, "max": 11, "result": "Warm and sunny" }, { "min": 12, "max": 18, "result": "Temperate and variable" }, { "min": 19, "max": 20, "result": "Unbearable heat" }] },
            { "id": "farm-npc", "description": "NPCs around the farm", "tags": ["npc", "farm"], "rng": [{ "min": 1, "max": 1, "result": "Marius the farmer, leaning on his shovel" }, { "min": 2, "max": 4, "prefix": "From the castle.. ", "table": "castle-npc" }, { "min": 5, "max": 8, "result": "Marius the farmer, harvesting potatoes" }, { "min": 9, "max": 11, "result": "Evelina the peasant woman who cleans the farmyard" }, { "min": 12, "max": 16, "result": "Raimondo the little rascal, who makes faces" }, { "min": 17, "max": 20, "prefix": "From the city.. ", "table": "city-npc" }] },
            { "id": "castle-npc", "description": "NPCs around the castle", "tags": ["npc", "castle"], "rng": [{ "min": 1, "max": 1, "result": "The wizard, who looks at you curiously" }, { "min": 2, "max": 4, "result": "Battista the butler, who looks at you suspiciously" }, { "min": 5, "max": 8, "result": "Maria the cook, who looks at you distractedly" }, { "min": 9, "max": 11, "result": "The castle gamekeeper" }, { "min": 12, "max": 18, "result": "Two students of magic, disciples of the castle wizard" }, { "min": 19, "max": 20, "result": "The wizard of the castle looking out of breath" }] },
            { "id": "city-npc", "description": "NPCs around the city", "tags": ["npc", "city"], "rng": [{ "min": 1, "max": 1, "result": "The mayor's wife" }, { "min": 2, "max": 4, "result": "The mayor" }, { "min": 5, "max": 8, "result": "A market trader" }, { "min": 9, "max": 11, "result": "Two city guards" }, { "min": 12, "max": 18, "result": "A citizen who looks at you with curiosity" }, { "min": 19, "max": 20, "result": "A schoolgirl from the city" }] },
            { "id": "farm-animals", "description": "Animals around the farm", "tags": ["animals", "farm"], "rng": [{ "min": 1, "max": 1, "result": "A lone wolf, out of the woods" }, { "min": 2, "max": 4, "result": "A stray cat purring around your legs" }, { "min": 5, "max": 8, "result": "One of the farm dogs, barking at you" }, { "min": 12, "max": 18, "result": "Hens squawking and chasing each other" }, { "min": 19, "max": 20, "result": "Castle hunting dogs, chasing a rabbit" }, { "min": 9, "max": 11, "prefix": "", "table": "", "postfix": "", "result": "A group of sheep, looking at you with curiosity" }]}
        ],
    "copiedContent": null,
    "clipboardAction": null,
    "tabPaths": ["farm", "", "", "", ""],
    "lastTableContent": {},
    "setpieces": [{ "id": "farm-setpiece", "description": "Places in the farm", "tags": [], "rng": [{ "min": 1, "max": 1, "description": "Courtyard", "textContent": "<h1>Courtyard</h1><p>In this courtyard you find the following animals:</p><ul><li>@@01</li><li>@@02</li><li>@@03</li></ul>", "table": "farm-animals! farm-animals! farm-animals!", "minAppears": 0, "maxAppears": 1000, "width": 1, "height": 1, "imgUrl": "" }, { "min": 2, "max": 2, "description": "Booth", "textContent": "<h1>Booth</h1><p>In this booth you find:</p><ul><li>@@01</li><li>@@02</li></ul>", "table": "farm-animals! farm-npc!", "minAppears": 0, "maxAppears": 1000, "width": 1, "height": 1, "imgUrl": "" }, { "min": 3, "max": 3, "description": "Orchard", "textContent": "<h1>Orchard</h1><p>In this orchard you find an animal, @@01&nbsp;</p><p>There is also an intruder from the city: @@02</p>", "table": "farm-animals! city-npc!", "minAppears": 0, "maxAppears": 1000, "width": 1, "height": 1, "imgUrl": "" }] }],
    "dungeonMonsters": [],
    "dungeonTreasures": [],
    "dungeonTrapSets": [],
    "dungeonSetpieces": [],
    "dungeonPuzzles": [],
}

export default initialContent;
